### ISSUE TITLE
Only unmount distribution point only if it wasn't mounted at start

### ISSUE THREAD

**Issue by magnusviri** [sheagcraig/JSSImporter#100]
Right now the JSSImporter unmounts the Jamf distribution point after each recipe, regardless of the status before the recipe runs.  It would be nice if the status is checked before it's run to see if it's already mounted, and if it is, to not unmount it when done.

**Comment by sheagcraig** [comment]
That seems reasonable. I'll look into it.

**Comment by sheagcraig** [comment]
Done.
