### ISSUE TITLE
Make it possible for overrides to disable script, group, and extension attribute creation.

### ISSUE THREAD

**Issue by magnusviri** [sheagcraig/JSSImporter#102]
This is an extension of the issue I opened titled "Allow turning off everything but package upload".

I didn't know that specifying an empty POLICY_TEMPLATE would skip policy creation and it looks like jss-recipes all have policy templates that can be overridden.

But the recipes in the jss-recipes repo that have extension attribute, group creation, and scripts do not have overrides.  It would be good if I could specify overrides for these that could disable the features, like how policy creation is disabled with a blank value for POLICY_TEMPLATE.

**Comment by sheagcraig** [comment]
You can do this with JSSImporter. But you can't do it with the AutoPkg organization's jss-recipes. It's not how they're written, it's not part of the accepted best-practices, etc.

I would recommend creating your own jss recipes for the products you need. If all you want to do is upload the package, you can write one jss recipe and then clone it for each desired product, just changing the parent recipe.
