### ISSUE TITLE
Don't mount sharepoint if there is no pkg_path

### ISSUE THREAD

**Issue by magnusviri** [sheagcraig/JSSImporter#104]
The documentation says that if you leave pkg_path it won't upload anything, but it will still mount the sharepoint.  (I'm using AFP).

**Comment by sheagcraig** [comment]
Should be able to fix this one pretty easily.

**Comment by sheagcraig** [comment]
Okay, got it in. Can you give me an idea of why you'd want to do a JSSImporter run for AutoPkg if there is no *pkg*? I'd like to add a bit of info to the README/wiki about this if it would be useful to others.
