### ISSUE TITLE
404 error when uploading installer packages to Jamf Cloud Distribution Point on AWS

### ISSUE THREAD

**Issue by rtrouton** [sheagcraig/JSSImporter#105]
I'm running into an odd 404 error with JSSImporter, where the package info gets uploaded but the package itself does not.

I'm uploading to a Jamf Cloud Distribution Point, hosted on AWS. I've verified that the package information shows up in the package listing in the Jamf Pro admin console, but the package does not appear in the S3 bucket when I look at the bucket via the AWS console. AutoPkg log is posted below.

[https://gist.github.com/rtrouton/cf2e3c00d035501daa5f27b881a3f6c4](https://gist.github.com/rtrouton/cf2e3c00d035501daa5f27b881a3f6c4)

**Comment by rtrouton** [comment]
I've also verified that the behavior is consistent. The usual fix is to delete the package info from the server and try again, but that doesn't work in this case.

**Comment by rtrouton** [comment]
This problem does not appear to be specific to JSSImporter, as I'm able to replicate similar behavior in Casper Admin. Fun!

Closing this issue, as it doesn't appear to be a problem specific to JSSImporter.

**Comment by sheagcraig** [comment]
Hmmm. So copying a package to a share is (unfortunately) a separate thing from creating a package object in Casper. Hopefully some day the API will expand to handle this for us.

**Comment by rtrouton** [comment]
It appears that this is a problem with Jamf Pro 9.98, with a fix coming in 9.99. I've also discovered that you don't want to enable server-side encryption for S3 buckets if you're using a cloud distribution point:

[http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html)

This policy denies upload permission to any files that don’t include the following header in the `PutObject` request:

`x-amz-server-side-encryption`

My guess is that file upload to a CDP don't currently include that header.

**Comment by rtrouton** [comment]
To follow up on this issue, my problem was resolved by installing Jamf Pro 9.99.0. Once the upgrade was completed, JSSImporter started working again without any changes.
