### ISSUE TITLE
Investigate package renaming at the JSSImporter level rather than recipe

### ISSUE THREAD

**Issue by sheagcraig** [sheagcraig/JSSImporter#107]
For context:
> elios [9:51 AM] 
I really wonder if the JSSImporter should be changed to rename pkgs name-version.pkg upon upload

> [9:52] 
Instead of 300 .pkg recipes all changed to use a name format required by one management tool

**Comment by macmule** [comment]
@sheagcraig would adding [FileMover](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/FileMover.py) as a def that appends version number to the pkg be all that you think is needed? (with an output of the new items pkg_path).

**Comment by sheagcraig** [comment]
@macmule I'm sure that would work.

Is this still an issue? Keep it open?
