### ISSUE TITLE
Initial install of imported software?

### ISSUE THREAD

**Issue by TheMattSchiller** [sheagcraig/JSSImporter#108]
So I have several autopkg recipes running with the JSSImporter, and they are all properly importing into JAMF, however, the clients I have in the static testing group never make it into the [appname]-update-smart group, therefore the software is never installed. I have tried forcing a JAMF recon and JAMF check-in. 

Am I missing something? Does the software already need to be installed before it can automatically be updated?

Thank you for any help and for making this tool!

**Comment by JayQ2** [comment]
@TheMattSchiller - That sounds right.  The smart group policy that gets created has the criteria "Application Title - is/has - <appname.app>"  meaning that application must already exist on the device to be added be added to self service. Must be meeting all three requirements.  The device is in the testing group, has the app already installed, and is not the newest version added to the smart group.

Firefox Example
<img width="595" alt="screen shot 2017-06-03 at 7 52 04 am" src="https://cloud.githubusercontent.com/assets/28454689/26754565/e0ba3b9e-4831-11e7-88a5-49df8b2bcb57.png">

**Comment by TheMattSchiller** [comment]
this was the case, thank you!!

**Comment by sheagcraig** [comment]
Awesome-thanks for the assist @JayQ2
