### ISSUE TITLE
JSS not being updated

### ISSUE THREAD

**Issue by jameslbrown** [sheagcraig/JSSImporter#110]
Using JSSImporter 0.5.1 with AutoPkgr 1.4.2 and AutoPkg 1.0.2

This used to work, but now no longer does. 

I get:

Error in com.github.jss-recipes.jss.MicrosoftWord: Processor: JSSImporter: Error: \__str\__ returned non-string (type Error)

Running JSS 9.99.0-t1494340586

Any ideas how to fix this?

Thanks, James.

**Comment by sheagcraig** [comment]
Hi James,
Based on that information, I don't know what's going on.

I would try it putting your entire output from running `autopkg run -vvvv MicrosoftWord.jss` here and even better into the AutoPkg or JamfNation channels on the Macadmins slack.
