### ISSUE TITLE
JamfCloud/SSO failure

### ISSUE THREAD

**Issue by agerstein** [sheagcraig/JSSImporter#112]
We moved our JSS to the cloud, and when I updated the URL in JSS Importer, it seemed to work - using the failover URL since the autopkgr account is local to the JSS, not in AD. I'm getting a green light in the JSSImporter config area, but when AutoPkgr does it's thing, I'm getting errors (below).

TL;DR: It looks like JSS Importer is working, but when it tries to do it's thing, our SSO is getting involved even though I don't think it's supposed to, and making things not work.

`Error in local.jss.Microsoft Excel: Processor: JSSImporter: Error: Error Parsing XML: <!doctype html>  <html class="no-js" data-module-type="AUTH" data-module-name="default"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <title>MySCSU Powered by Sailpoint</title> <link rel="icon" type="image/png" href="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/theme/images/favicon.png">  <link rel="apple-touch-icon-precomposed" href="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/theme/images/apple-touch-icon-precomposed.png"> <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/theme/images/apple-touch-icon-72x72-precomposed.png"> <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/theme/images/apple-touch-icon-114x114-precomposed.png"> <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/theme/images/apple-touch-icon-144x144-precomposed.png"> <link rel="stylesheet" type="text/css" href="https://login.southernct.edu/orgStyle/css?hash=65997c9bd54e925727da3dee2e4c3ff3"> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"> <link rel="stylesheet" href="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/styles/app.b926158d.css"> </head> <body id="slpt-auth-page" ng-app="cloudUiAuthApp" ng-csp="no-inline-style;no-unsafe-eval"> <section ui-view class="m-b"></section> <script src="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/scripts/vendor.93a4ff11.js"></script> <script src="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/scripts/scripts.148171d6.js"></script> <script src="https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/l10n/language-package.js"></script> <script src="https://files.accessiq.sailpoint.com/modules/builds/static-assets/perpetual/angular-i18n/1.6.3/angular-locale_en-us.js"></script> <script id="slpt-globals-json" type="application/json"> { "uiModuleType": "AUTH", "uiModuleName": "default", "uiModuleCache": "STATIC", "uiTemplateUrl": "https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/index.html", "uiTemplateBaseUrl": "https://d2cp8qnlnrfxq4.cloudfront.net/modules/builds/auth/build118/", "uiTemplateDomainUrl": "https://d2cp8qnlnrfxq4.cloudfront.net/", "locales": ["en"], "languagePackage": "default", "angularLocale": "en-us", "apiUrl": "https://login.southernct.edu", "goto": "https://login-sso.southernct.edu/sso/SSORedirect/metaAlias/scsu/idp?ReqID=a3e1ce9dj29e0g4b10jjigej53a77ih&index=null&acsURL=https%3A%2F%2Fsouthernct.jamfcloud.com%2Fsaml%2FSSO&spEntityID=https%3A%2F%2Fsouthernct.jamfcloud.com%2Fsaml%2Fmetadata&binding=urn%3Aoasis%3Anames%3Atc%3ASAML%3A2.0%3Abindings%3AHTTP-POST", "gotoOnFail": "https://login.southernct.edu/login/fail?goto=https%3A%2F%2Flogin-sso.southernct.edu%2Fsso%2FSSORedirect%2FmetaAlias%2Fscsu%2Fidp%3FReqID%3Da3e1ce9dj29e0g4b10jjigej53a77ih%26index%3Dnull%26acsURL%3Dhttps%253A%252F%252Fsouthernct.jamfcloud.com%252Fsaml%252FSSO%26spEntityID%3Dhttps%253A%252F%252Fsouthernct.jamfcloud.com%252Fsaml%252Fmetadata%26binding%3Durn%253Aoasis%253Anames%253Atc%253ASAML%253A2.0%253Abindings%253AHTTP-POST", "loginUrl": "https://login-sso.southernct.edu/sso/login", "error": "false", "orgScriptName": "scsu", "orgProductName": "MySCSU Powered by Sailpoint", "orgStandardLogoUrl": "https://sppcbu-images-useast1.s3.amazonaws.com/custom-logos/scsu/610117fd32d237ba650fa1fe26d8ba50.png", "orgNarrowLogoUrl": "https://sppcbu-images-useast1.s3.amazonaws.com/custom-logos/scsu/c29ff2aaec07d62d71a06224836e831d.png", "analytics": {"google":{"trackingId":"UA-47107321-4"}}, "sso": true, "hasNetworkConstraints": "false", "usernameLabel": "", "usernameEmptyText": "", "resetUrl": "https://login.southernct.edu/passwordreset", "rememberMe": "false" } </script> <input id="slptbx-pod" type="hidden" value="fiji" /> <input id="slptbx-version" type="hidden" /> <input id="slptbx-org" type="hidden" value="scsu" /> <input id="slptbx-debug" type="hidden" value="false" /> <input id="slptbx-auth" type="hidden" /> <input id="slptbx-listening" type="hidden" /> <input id="slptbx-ready" type="hidden" /> <input id="slptbx-user-encr-pass" type="hidden" /> <input id="slptbx-user-encr-key" type="hidden" /> <input id="slptbx-trigger-set-encr-pass" type="hidden" /> <input id="slptbx-trigger-get-encr-pass" type="hidden" /> <input id="slptbx-trigger-get-encr-key" type="hidden" /> <input id="slptbx-trigger-set-encr-key" type="hidden" /> <input id="slptbx-trigger-reset-login-timestamps" type="hidden" /> <input id="slptbx-trigger-update-link-scripts" type="hidden" /> <input id="slptbx-trigger-app-profile-generator" type="hidden" /> <input id="slptbx-trigger-app-profile-uuid" type="hidden" /> <input id="slptbx-user-key" type="hidden" value="" /> <input id="slptbx-sid" type="hidden" value="" /> <input id="slptbx-bootstrap-url" type="hidden" value="https://login.southernct.edu/bx/bootstrap" /> <input id="slptbx-version" type="hidden" /> </body> </html>
`

**Comment by agerstein** [comment]
So, never mind - we moved our cloud based JSS to use LDAP authentication, so the SSO isn't involved and it's "just working" again.

**Comment by sheagcraig** [comment]
Phew!

**Comment by sheagcraig** [comment]
Glad that it's working again for you!
