### ISSUE TITLE
Overwrite JSS_URL and other parameters in recipe_override?

### ISSUE THREAD

**Issue by grahampugh** [sheagcraig/JSSImporter#114]
I'm trying to think of a way to get AutoPkg to push to multiple JSSes, because the JSS API doesn't have enough features to successfully do API policy transfers from one JSS to another (e.g. transfer of self-service icons). One method I can think of would be to have different recipe overrides for each JSS instance. However, as far as I can see at the moment, JSSImporter only looks at the AutoPkg preferences for the JSS_URL information. If this could be overridden in a recipe override, I could create multiple overrides for the same package.

**Comment by ryangball** [comment]
You might look at this for migration: https://github.com/igeekjsc/JSSAPIScripts

**Comment by grahampugh** [comment]
Thanks,  I looked at various resources including that one, but they all strip out the self service icon data for policies. I've now figured out how to do it in a roundabout way, so this ticket can now be closed. 

Cheers, 
Graham

**Comment by sheagcraig** [comment]
Late to the party, but FWIW you can indeed run 1 override per JSS and override the settings needed in the override. That seems like cheating, but it's definitely one way of doing it. You can also create 1 service account per JSS and have each one run AutoPkg independently, which is also a little nutty.

A guess a third option is to write a LaunchDaemon to run AutoPkg with the -l "list" option on a schedule, changing the JSS_URL etc prefs in-between runs.
