### ISSUE TITLE
Getting kNAUIOptionNoUI error when running jss recipe on High Sierra

### ISSUE THREAD

**Issue by smashism** [sheagcraig/JSSImporter#115]
Getting the following error on High Sierra GM using AutoPkgr + autopkg + jssimporter:

> autopkg run THD_iTerm2.jss
> Processing THD_iTerm2.jss...
> 'kNAUIOptionNoUI'
> Failed.
> 
> The following recipes failed:
>     THD_iTerm2.jss
>         Error in THD_iTerm2.jss.recipe.local: Processor: JSSImporter: Error: 'kNAUIOptionNoUI'
> 
> Nothing downloaded, packaged or imported.

When running the recipe was a pkg recipe it works fine. Seems to be something with jssimporter.

**Comment by pauldalewilliams** [comment]
This is actually an issue with the python-jss module, specifically it's use of the NetFS.framework API.  I've submitted an issue here:  https://github.com/sheagcraig/python-jss/issues/62

**Comment by smashism** [comment]
Thanks @pauldalewilliams. Closing this in leu of https://github.com/sheagcraig/python-jss/issues/62.
