### ISSUE TITLE
When readme is migrated to wiki, add FAQ page

### ISSUE THREAD

**Issue by smashism** [sheagcraig/JSSImporter#123]
The issue of not having the requests module and how to install it (and pip if that isn't installed either) should be one of the FAQs for sure. Comes up a lot on the Slack.

**Comment by sheagcraig** [comment]
Agreed. You don't need requests any more (once we sort out CDP uploads that is), so while we could definitely use a FAQ page, the requests dependencies issues are going away.

Anybody want to volunteer to collect any FAQ items? I believe the Wiki is public!

**Comment by smashism** [comment]
If you can get a wiki template started I'm sure folks can chime in :)

**Comment by sheagcraig** [comment]
Will do!

**Comment by sheagcraig** [comment]
Done!

**Comment by smashism** [comment]
I get a `You do not have permission to update this wiki.` when I try to click on the FAQ page. :(

**Comment by sheagcraig** [comment]
Boo! That's weird. The settings page says any user can create pages... But that page hadn't been created really, just linked, so I'm not sure what's up.

I created the empty FAW page; want to try again? I don't see any obvious "let everybody use your wiki like a wiki is supposed to be used" button anywhere.

**Comment by sheagcraig** [comment]
Or... I just missed it completely. Open now-sorry for the runaround!
