### ISSUE TITLE
How to scope differently

### ISSUE THREAD

**Issue by charliwest** [sheagcraig/JSSImporter#27]
I am trying to set up a fairly fully automated system using this and autoupdate magic. I have hit a bit of a stumbling block though.
I will try and explain fully further down my flow, but in short I would like to have override recipes that make an install policy triggered by autoupdate-%PROD_NAME% scoped to a smart group, something like update-%PROD_NAME%-Real, but in the PolicyTemplate.xml for scope it says is added by JSSImporter. So basically how do I create the policy with a different scope?

Longer flow example is:-
AutoPkg with JSSImporter updates Firefox, smart group is created 'Firefox-update-smart', this has one criteria that they are part of the static group 'Testing', policy is created to install via self service, scoped to  'Firefox-update-smart'.
Then I would like my testers to install it, report back all is good, then someone runs a script to say 'make real Firefox'. This then calls AutoPkg with JSSImporter to run the policy making part again, but this time with different templates 'SmartGroupReal.xml' and 'PolicyReal.xml' but the policy still scopes to testing

**Comment by charliwest** [comment]
OK, litteraly while writing this I realised where I was going wrong, I obviously need two smart groups, 'Firefox_update_smart_testing' and 'Firefox_update_smart_real' as an example and then JSSImporter will scope to the new group and I can trigger it with trigger other.

Thats correct isn't it?

**Comment by sheagcraig** [comment]
That sounds correct to me.

Your second comment seems to indicate you're on the track of taking a policy that allows testers to install a package, run a script  to update the policy, and then the same policy is scoped to a different, broader group.

The problem I foresee with that approach is that when the next update comes out, it knocks out the scope that is delivering the software to your broader users and replaces it with the testing scope again. And it's a self-service policy, so it wasn't automatically distributed.

I would think that just having two policies would be best (and maybe I'm misinterpreting your design above). One for testing, that just constantly has the newest version, and then the production one.

In terms of autopkg, you could, in your release (I call it "promotion") script, *use* the package that is already up there.

I wrote a utility called jss_helper to do this manually for me, but it could be turned into an automated thing. You just feed it the package ID of the old package, the new package, and the policy, and it does all of the swapping around. If the numbers don't make sense it bails.

The only problem is that you have to manually flush the policy logs if you're using a "Once per computer" install frequency, but that can be solved with the scope (and it sounds like you have a good plan for that).
