### ISSUE TITLE
Post JSS 9.65 packages uploaded with JSSImporter do not sync to JDS

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/JSSImporter#29]
So just noticed that packages run from existing .jss recipes that worked fine in 9.63 are failing to sync to JDS in 9.65.  Let me know what you need to diagnose.

**Comment by everetteallen** [comment]
Ok never mind, looks like the issue is around putting a package of the same name but different display names in by both the web interface and the api.

**Comment by sheagcraig** [comment]
Phew! That's good. I was sweating that they had changed something!
