### ISSUE TITLE
Unverified HTTPS request is being made?

### ISSUE THREAD

**Issue by stevehillnz** [sheagcraig/JSSImporter#30]
Not sure where to raise this issue.  I have searched through all the autopkg issues and have found similar, but not the same.

We have two repositories: one uses smb, the other afp. This is a new installation of autopkg, attempted on both 10.9 and 10.10 machines with the same outcome.  JSS is version 9.65.  Authentication with JSS and Repos is good.

When running recipes all goes well until:

```
26/02/2015 3:28:13.526 pm AutoPkgr[726]: (FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 674, in main
    self.handle_icon()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 559, in handle_icon
    icon.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 1181, in save
    self.jss._error_handler(JSSPostError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/jss.py", line 174, in _error_handler
    raise exception
jss.exceptions.JSSPostError: JSS Error. Response Code: 409	Response" Conflict
Unable to complete file upload.  File contents does not match file type.
```

Followed by:
```
26/02/2015 3:28:13.527 pm AutoPkgr[726]: [DEBUG] Error [1] Error running recipes 
 /Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/contrib/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

This repeats many times ending with :

```
A Python exception occurred during the execution of autopkg, see the console log for more details.
[ERROR] Unable to complete file upload.  File contents does not match file type.
```

That's where is all comes to a stop.  All ideas welcomed.

**Comment by sheagcraig** [comment]
There are a couple of issues going on here:
- The icon is failing to upload.
- urllib3 is complaining that you're performing insecure web requests.

One of these is a problem, the other is just nagging.

More specifically, urllib3 and requests, the python modules which handle all of the API requests are complaining that you're not using HTTPS for your communications. Of course this requires a properly set up JSS with a valid certificate, which you may not have at the moment. So you've (I'm assuming) set ```JSS_VERIFY_SSL``` to ```false``` in your AutoPkg(r) preferences.

To suppress the nagging you need to add another key: ```JSS_SUPPRESS_WARNINGS``` = ```true```. This may or may not be available in the current autopkgr version, so you may have to set it yourself, i.e.
```defaults write com.github.autopkg JSS_SUPPRESS_WARNINGS -bool true```

As for the icon uploading issue, see #34 also. I've never seen the JSS report this error before, and I wonder if it is an issue with the new JSS version 9.65 (or > 9.6, which is what we're using at the moment).

Some ideas:
- Icons are only ever uploaded *once*. So if you've never run a recipe that uploads an icon, this is definitely what's going on. If you've already successfully uploaded this icon and it's failing, something else is going on.
- I imagine you're using the recipes in my jss-recipes repo. Many people have been using these successfully, so I feel pretty confident that the files are *indeed* PNG files! Again, perhaps JAMF has changed the value for the file type or something. I'll need to update our testing server to fool around with this.

In the meantime, if you're wanting to just get recipes running, I suspect you could override the recipes to have a blank ```ICON``` value. This will skip icon upload and hopefully move on to the rest of the recipe.

Let me know how it goes, and I'll do some research on my end.

**Comment by sheagcraig** [comment]
Wanted to keep you in the loop: JSS v9.65 is rejecting file uploads for me too. I just upgraded a test server and can see the same problems. I have submitted a support request with JAMF: Hopefully it will be something simple!

**Comment by stevehillnz** [comment]
As predicted, suppressing those warnings killed the nagging.
Standing by for JAMF's response to the icon issue.

**Comment by sheagcraig** [comment]
@stevehillnz , please manually update python-jss (or just reinstall JSSImporter, since it will run the manual shell command below) with
```
easy_install -U python-jss
```
and you should be able to upload icons again (which is the problem here).

When I get a chance, I'll also update the JSSImporter.

And when JAMF figures out the regression, I'll fix python-jss back up.
