### ISSUE TITLE
Error when appending a Script to a Policy

### ISSUE THREAD

**Issue by ChrOst** [sheagcraig/JSSImporter#32]
Hi,

I've a Problem adding a script to a policy.

```
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 706, in main
    self.scripts = self.handle_scripts()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 542, in handle_scripts
    update_env="jss_script_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 524, in _update_or_create_new
    recipe_object.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.4-py2.7.egg/jss/jss.py", line 626, in save
    "Object Conflict! If trying to post a new "
jss.exceptions.JSSPostError: Object Conflict! If trying to post a new object, look for name conflict and delete.

```

Updated the python-jss to the testing tree - still happens the same way.

The Script is already within the JSS (it got uploaded once using the ScriptTemplate function) but now it crashes :(
Too bad, since thats the way I wanted to allow the Users to switch between Java 7 and Java 8.

I'll try to figure out a resolution myself - but any help is welcome ;)

Best Regards,
ChrOst

**Comment by ChrOst** [comment]
Just to have the full info's and files i have here...
the part of including the script to the policy:
```
<key>scripts</key>
<array>
  <dict>
    <key>name</key>
    <string>DeleteOtherJava</string>
    <key>template_path</key>
    <string>%RECIPE_DIR%/DeleteOtherJava.xml</string>
  </dict>
</array>
```

and the DeleteOtherJava.xml

```
<script>
  <name>DeleteOtherJava.sh</name>
  <category>System</category>
  <filename>DeleteOtherJava.sh</filename>
  <info/>
  <notes/>
  <priority>Before</priority>
  <parameters/>
  <os_requirements/>
</script>
```

**Comment by sheagcraig** [comment]
Has the recipe run successfully *more than once* with those settings?

My immediate guess is that the ```name``` in the recipe scripts array is incorrect. It should be the filename of the script you wish to upload (even though it unfortunately and deceptively looks like it should be the human-readable name for the web interface). If you change it to match the filename of DeleteOtherJava.sh does it work correctly?

**Comment by ChrOst** [comment]
Your guess was right - could have seen this too - but I guess I didnt see it after 10hrs of editing xml files ;)

Thanks @sheagcraig

**Comment by sheagcraig** [comment]
Cool! Glad it worked.
