### ISSUE TITLE
Java8

### ISSUE THREAD

**Issue by JonMunford** [sheagcraig/JSSImporter#34]
When I use your java8 recipe I get the error.
[ERROR] Unable to complete file upload. File contents does not match file type.

It is not happen with any other recipe's that i'm using.

Any thoughts?

Thanks!

**Comment by sheagcraig** [comment]
Hey Jon,
I just ran it and it worked fine for me, and I've never seen that JSS error before today (but see below).

I'm guessing the error above is actually complaining about the icon, not the package? If you run autopkg with the ```-v``` argument you should get messages about each step of the processor and what is happening. If you could run the recipe with that ```-v``` and add the (sanitized if need be) output to the issue, that may help.

Issue #30 seems to (among other things) be having a similar error: "File contents does not match file type." This is an error that the JSS is reporting. For them, it seems to be failing on *all* recipes at the icon stage (need to confirm with @stevehillnz. Is yours also failing at icon upload? You're just using the icon that comes stock with the recipe repo, I imagine?

Also, are you using JSS version 9.65? It's possible that 9.65 adds some kind of filetype verification that I haven't come across yet. That being said, it's most definitely a PNG that comes in the repo... I've used it here successfully for awhile now.

Let me know!

**Comment by JonMunford** [comment]
Thanks for the fast response!  I ran that in verbose mode and here is what i'm getting.

autopackager:~ administrator$ autopkg run -v OracleJava8.jss
Processing OracleJava8.jss...
URLTextSearcher
URLTextSearcher: Found matching text (url): http://download.oracle.com/otn-pub/java/jdk/8u31-b13/jre-8u31-macosx-x64.dmg
URLTextSearcher: Found matching text (match): http://download.oracle.com/otn-pub/java/jdk/8u31-b13/jre-8u31-macosx-x64.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/downloads/OracleJava8.dmg
EndOfCheckPhase
FlatPkgUnpacker
FlatPkgUnpacker: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/downloads/OracleJava8.dmg
FlatPkgUnpacker: Unpacked /private/tmp/dmg.cruiUe/Java 8 Update 31.pkg to /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack
PkgRootCreator
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/root
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/root/Library
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/root/Library/Internet Plug-Ins
PkgRootCreator: Created /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/root/Library/Internet Plug-Ins/JavaAppletPlugin.plugin
PkgPayloadUnpacker
PkgPayloadUnpacker: Unpacked /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/javaappletplugin.pkg/Payload to /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/root/Library/Internet Plug-Ins/JavaAppletPlugin.plugin
PlistReader
PlistReader: Reading: /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/unpack/root/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Enabled.plist
PlistReader: Assigning value of '1.8.31.13' to output variable 'version'
PkgCopier
PkgCopier: Mounted disk image /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/downloads/OracleJava8.dmg
PkgCopier: Using path '/private/tmp/dmg.mAdkW5/Java 8 Update 31.pkg' matched from globbed '/private/tmp/dmg.mAdkW5/Java*.pkg'.
PkgCopier: Copied /private/tmp/dmg.mAdkW5/Java 8 Update 31.pkg to /Users/administrator/Library/AutoPkg/Cache/local.jss.OracleJava8/OracleJava8-1.8.31.13.pkg
JSSImporter
JSSImporter: Category type: category-'Plugins' already exists according to JSS, moving on...
JSSImporter: Category type: policy_category-'Auto Update' already exists according to JSS, moving on...
JSSImporter: Pkg-object already exists according to JSS, moving on...
JSSImporter: ComputerExtensionAttribute: OracleJavaVersion updated.
JSSImporter: ComputerGroup: ^OracleJava8-update-smart updated.
JSSImporter: Policy: Auto Update OracleJava8 updated.
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 608, in main
    self.handle_icon()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 503, in handle_icon
    icon.save()
  File "/Library/Python/2.7/site-packages/python_jss-0.5.3-py2.7.egg/jss/jss.py", line 1157, in save
    self.jss._error_handler(JSSPostError, response)
  File "/Library/Python/2.7/site-packages/python_jss-0.5.3-py2.7.egg/jss/jss.py", line 161, in _error_handler
    raise exception
jss.exceptions.JSSPostError: JSS Error. Response Code: 409	Response" Conflict
Unable to complete file upload.  File contents does not match file type.

**Comment by sheagcraig** [comment]
I'm hearing from others on twitter that 9.65 is rejecting icon uploads with that error. So it's either an API change that wasn't mentioned in the release notes or a bug in the new JSS.

Technically, I think you could add the icon manually through the web interface once, and then the recipe won't try to upload it again and the recipe won't need editing. This would get you through until we figure out what is going on.

Otherwise, overriding the ```ICON``` value to be a blank value will skip the icon handling for the time being.

**Comment by JonMunford** [comment]
Ok.  I'll just upload it for now manually.  I wonder if i'm not hearing an issue with the other recipes because their icons were uploaded before i went to 9.65.  

Thanks, I really appreciate your help with this issue and with the project as a whole!

**Comment by JonMunford** [comment]
Just to confirm, when I manually uploaded the image to the JSS the recipe did work fine.

Thanks!

**Comment by sheagcraig** [comment]
Thanks @JonMunford . I have installed 9.65 and confirmed that it does not work as expected. I have submitted a support case with Jamf about it. Hopefully it's something simple!

**Comment by charliwest** [comment]
Quick note to add, I had the same error when running iTerm2 recipe, I found the recipe asks for a png called iTerm.png, which although I had in the dir, I guess it really should have been using iTerm2.png, which was also there, the files are different sizes etc etc, with iTerm2.png in the recipe it worked. Perhaps the checking on the pic files has become more strict?

**Comment by sheagcraig** [comment]
Folks, please manually update python-jss (or just reinstall JSSImporter, since it will run the manual shell command below) with
```
easy_install -U python-jss
```
and you should be able to upload icons again (which is the problem here).

When I get a chance, I'll also update the JSSImporter.

And when JAMF figures out the regression, I'll fix python-jss back up.

**Comment by ChrOst** [comment]
Currently 
```easy_install -U python-jss```
breaks it. 
jss.contrib.requests.exceptions.SSLError: [Errno 185090050] _ssl.c:343: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

**Comment by sheagcraig** [comment]
@ChrOst

Your error has to do with not being able to find the certificate bundle included with the builtin HTTP library requests.

Please try re-installing the latest JSSImporter package and see if things still give you issues. I would like to see a full verbose log of any errors if you're still having issues; and please add it as a new issue. Thanks!

**Comment by ChrOst** [comment]
Yep. Did that now. Fixes it.

I just got some things a added which scared me to update JSSImporter.
But it seems to work well.

Thanks (y)
