### ISSUE TITLE
Enhancement: Batch all the JSS imports to the end of the bulk run

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSImporter#39]
When multiple .jss recipes are called in bulk, JSSImporter constantly mounts and unmounts the distribution point as individual recipes are processed. It would be more efficient to queue up all the .pkg files from the individual recipe runs, and then import them to the JSS all together at the end. (Something like the way MakeCatalogs.munki runs after a batch of .munki recipes.)

Maybe possible, maybe not, but it seems like the kind of idea that would be worth suggesting.

**Comment by sheagcraig** [comment]
@homebysix I think that sounds like a good idea. My concern is that with the current state of exception handling in AutoPkg, it's quite possible that a recipe further down the list fails, and then NONE of the packages get copied.

Also, there's no precedent in AutoPkg of a processor deferring work until later. So it would have to happen at an AutoPkg level, or at least JSSImporter would have to put in place some LaunchDaemons or something to run later. Which I think is probably getting a little crazy.

Ideally, AutoPkg is really only picking up updates here and there, so the copying speed advantages that you may be able to achieve from batching the uploads are probably small. Sure, the first time you run your giant list of packages it will grab a bunch of updates (1:1), but after that you should only get a few. I think this one is kind of a longterm-let's-see-what-shakes-loose-in-AutoPkg-proper idea.
