### ISSUE TITLE
Possible to fill Info or Notes fields for packages

### ISSUE THREAD

**Issue by quovadimus** [sheagcraig/JSSImporter#41]
Is it possible to add information to the 'Info' or 'Notes' fields for packages?  We use those to keep track of the technician working on a particular item, or its testing status.  I'd like to be able to add something basic from autopkg when new packages are added, perhaps a flag to indicate a NEW item.

I was hoping I'd be able to utilize the same methods you use to write to the Category or Display Name fields, but alas, its a little beyond my skills.

Thanks!

**Comment by sheagcraig** [comment]
@quovadimus It's totally possible. Unlike the Policy and Group objects, the Package doesn't have a template; it has hardcoded inputs. I'll add in Info and Notes arguments to the next release.

**Comment by quovadimus** [comment]
thats wonderful!  Thank you.

**Comment by quedayone** [comment]
Want as well.

**Comment by sheagcraig** [comment]
Update: Working on this NOW.

**Comment by sheagcraig** [comment]
Implemented in JSSImporter 0.5.0.
