### ISSUE TITLE
PKG is not imported if run on the same machine as the JSS

### ISSUE THREAD

**Issue by rougegoat** [sheagcraig/JSSImporter#42]
I set up AutoPkgr+JSSImporter+Autopkg+Git on a test machine with everything working fine.  Packages imported just fine and policies/scopes/etc were created as expected.  I wanted to ensure that the scheduled runs would be on a machine that was always on, so I did the same setup on the server currently hosting our JSS.  Same setup steps were followed in both places.

When I run a test job(Skitch.jss from either terminal or AutoPkgr), it completes without errors.  If I switch to the JSS web view, I see the policy/group/etc was created successfully and all appears well.
![screen shot 2015-05-07 at 11 59 42 am](https://cloud.githubusercontent.com/assets/541022/7521172/7e83c1aa-f4b1-11e4-8133-e724e7fcef2e.png)

It fails if pushed though.  Looking into Casper Admin shows the file as listed but missing.
![screen shot 2015-05-07 at 12 02 20 pm](https://cloud.githubusercontent.com/assets/541022/7521183/92ec9568-f4b1-11e4-9f8e-61553df800b8.png)
I manually checked the Packages folder and the pkg is not present.

So it appears that the JSS database is updated correctly but the file never gets placed into the correct folder.  Since it is happening with both the terminal and the gui, I've ruled out AutoPkgr.  Everything builds correctly, so I'm thinking it's related to JSSImporter and not AutoPkg.

I'm not sure how to enable verbose logging with JSSImporter so unfortunately I have no idea what it's reporting back when it fails to transfer the file.  I can provide more detail if needed.

**Comment by rougegoat** [comment]
Resolved by configuring Distribution Points and pointing it back at itself.  Ticket can be closed.

**Comment by sheagcraig** [comment]
Aha! Great! I'm glad that you were able to resolve this. It will happily plug along with no distribution points set up, which can cause the issue you were seeing above. I think it may make sense in the future to avoid creating package objects on the server if there are no distribution points onto which the package can then be copied... Let me think about that and possibly throw into the next update.
