### ISSUE TITLE
Seeing auth issue on after 0.5.0

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/JSSImporter#46]
So was just working and now get this.  Both command line and with AutoPkgR.

===
itdhcp10136:~ oitadmin$ autopkg run /Users/oitadmin/Library/AutoPkg/OverRides/UNCSystem-AutoPKG-SketchUp.jss.recipe 
Processing /Users/oitadmin/Library/AutoPkg/OverRides/UNCSystem-AutoPKG-SketchUp.jss.recipe...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1651, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1645, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1458, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 470, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 299, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 920, in main
    self.scripts = self.handle_scripts()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 671, in handle_scripts
    update_env="jss_script_updated")
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 534, in _update_or_create_new
    recipe_object.save()
  File "/Library/Python/2.7/site-packages/python_jss-1.2.0-py2.7.egg/jss/jss.py", line 670, in save
    raise JSSPutError(put_error)
jss.exceptions.JSSPutError: Response Code: 401	Response: Unauthorized. The request requires user authentication
===

**Comment by sheagcraig** [comment]
Hey @everetteallen : Keeping me honest again, I see.

That's very strange that the authorization stuff should change at all here. Nothing was changed!

Can you clarify what you mean by version 0.5.0, since both AutoPkg and JSSImporter have that version number currently (you probably mean both, since you're using AutoPkgr).

The error you referenced above is specifically stating that your SketchUp recipe is trying to PUT a script object, and the account set up to do so does not have the scripts update privileges.

I have heard about people updating AutoPkgr and it actually blanks out and removes their API_USERNAME and API_PASSWORD settings from the Autopkg preferences.

Can you confirm the correct prefs with `defaults read com.github.autopkg API_USERNAME` and `defaults read com.github.autopkg API_PASSWORD`?

**Comment by everetteallen** [comment]
So turns out the JDS Repos section was missing from the autopkg prefs 
file.  My guess is AutoPKGR got it during an upgrade and using their 
check box in the new config panel does not seem to work.
For the record I do have 0.5.0 for both autopkg and jssimporter and I 
did an upgrade to AutoPKGR 1.3(1002) today with same issue.  The manual 
recreation of missing config section did the trick.


On 7/27/15 1:08 PM, Shea Craig wrote:
> Hey @everetteallen <https://github.com/everetteallen> : Keeping me
> honest again, I see.
>
> That's very strange that the authorization stuff should change at all
> here. Nothing was changed!
>
> Can you clarify what you mean by version 0.5.0, since both AutoPkg and
> JSSImporter have that version number currently (you probably mean both,
> since you're using AutoPkgr).
>
> The error you referenced above is specifically stating that your
> SketchUp recipe is trying to PUT a script object, and the account set up
> to do so does not have the scripts update privileges.
>
> I have heard about people updating AutoPkgr and it actually blanks out
> and removes their API_USERNAME and API_PASSWORD settings from the
> Autopkg preferences.
>
> Can you confirm the correct prefs with |defaults read com.github.autopkg
> API_USERNAME| and |defaults read com.github.autopkg API_PASSWORD|?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheagcraig/JSSImporter/issues/46#issuecomment-125274227>.
>

-- 
Everette Gray Allen		Systems Programmer II
Office of Information Technology	Apple Support Specialist
2620 Hillsborough St, Campus Box 7109
Raleigh, NC 27695-7109  AIM: EveretteAlln
919-515-4558		Everette_Allen@ncsu.edu

**Comment by sheagcraig** [comment]
Great!

**Comment by everetteallen** [comment]
So just to be complete there were actually 2 issues. Either the fault of JSSImporter as best I can tell.  The first was the missing JDS Repos.  For the second your comment about uploading a script made me trace the recipe chain and encounter my first recipe with a script and and app.  So it  is true that we do not allow scripts uploads and that is what gave the error reported.  FYI

**Comment by WTaylorA** [comment]
I'll probably start a new thread as well, but running into the same error.  I'm simply testing with the AdobeFlashPlayer.jss recipe as a test.  I'm seeing both of my distribution (non-JDS, just one SMB and one AFP share) mounted, so the authentication piece there is working, but I'm at bit of a loss beyond that.  

(edit  - also tested Firefox and Google Chrome recipes just to make sure it wasn't a bug, same result.  Same error also from the terminal:

Processing AdobeFlashPlayer.jss...
Error mounting url "smb:/<server>: None
Failed.

The following recipes failed:
    AdobeFlashPlayer.jss
        Error in com.github.jss-recipes.jss.AdobeFlashPlayer: Processor: JSSImporter: Error: Error mounting url "smb://<server>": None

The following packages were copied:
    Pkg Path                                                                                                       
    --------                                                                                                       
    /Users/test/Library/AutoPkg/Cache/com.github.jss-recipes.jss.AdobeFlashPlayer/AdobeFlashPlayer-20.0.0.235.pkg
