### ISSUE TITLE
Too long Button Text

### ISSUE THREAD

**Issue by ChrOst** [sheagcraig/JSSImporter#47]
... can result in a 
`jss.exceptions.JSSPutError: Response Code: 409  Response: Conflict. Unable to update the database`

Not sure where to place this note, but atleast you now can find this using google ;)

**Comment by sheagcraig** [comment]
I'll look for a way to error out informatively if too-long button text is added to a recipe. What is the specific object / tag that freaks out about this?

**Comment by ChrOst** [comment]
```
<policy>
	<self_service>
		<use_for_self_service>true</use_for_self_service>
		<install_button_text>a freaking long button text which will fail for sure</install_button_text>
	</self_service>
</policy>
```
install_button_text is the bad one :-)

**Comment by sheagcraig** [comment]
@ChrOst do me a favor and let me know what the max length that will fit would be. I'd love to get this in for the next release, but I don't actually have a JSS!

**Comment by ChrOst** [comment]
![image](https://user-images.githubusercontent.com/7702426/31216274-564cf26a-a9b3-11e7-9831-d80f8916eea7.png)
32 Chars is the Limit :-)

**Comment by sheagcraig** [comment]
Just to confirm-that's <= 32, or < 32?

**Comment by sheagcraig** [comment]
Hmm. The max length is 31 characters.

Version 9.101 seems to accept too-long button text and just truncates it to 31 characters, so I'm going to say this is solved moving forward.
