### ISSUE TITLE
Cannot mount DPs...

### ISSUE THREAD

**Issue by stillmacn** [sheagcraig/JSSImporter#50]
First off, thanks to Elliot Jordan for suggestions and pointing me here..

I looked at various leads via the suggestions given but ultimately I am here: AutoPkgr fails because it cannot mount any of my DP's. I'm running AutoPkgr 1.3 and JSS 9.72. I've checked my passwords and all appears correct (including testing with different accounts and special and non-special characters). I can AFP and SMB mount the shares through the Finder with no issue.

I've tried running directly from server and from admin workstation with same results.

subprocess.CalledProcessError
: Command '['mount', '-t', 'afp', u'afp://account:*******@server.gov:548/CasperShare', u'/Volumes/CasperShare']' returned non-zero exit status 97

Not running a JDS. Any thoughts greatly appreciated!

**Comment by jmb03012** [comment]
I had the exact same problem and worked with Shea to resolve it.  The solution was ultimately an egg for Python JSS that contained different mount scripts.

@sheagcraig this was the mount_shares_better.py that I'm currently running from you I believe?

**Comment by stillmacn** [comment]
Thanks @jmb03012

**Comment by sheagcraig** [comment]
@stillmacn If you can wait a just a bit, I've been wrapping up a fairly large release for python-jss that uses new mounting code (rather then shelling out to the mount command, it uses the underlying Apple frameworks to do it).

Hopefully I can get this going very soon (next few days).

Alternately, if you feel comfortable doing so, you can grab the testing version from GitHub and use that until the official release comes out.

**Comment by stillmacn** [comment]
@sheagcraig thanks for the update.

**Comment by sheagcraig** [comment]
@stillmacn Have you tried that latest release of python-jss (1.3.0)? It uses the new mount code.

A new new release is coming out today, but that shouldn't really have any changes.

**Comment by stillmacn** [comment]
@sheagcraig I did not as we have been prepping for a switch from DP to JDS which we should be completing by the end of the week. That being said, I will wait for the new new today and then try again from there...

**Comment by stillmacn** [comment]
@sheagcraig This is working now, thanks! Consider it closed!
