### ISSUE TITLE
Support for HTTP/HTTPS Only Distribution Points

### ISSUE THREAD

**Issue by rougegoat** [sheagcraig/JSSImporter#53]
We recently set up [Box as a Distribution Point](https://bryson3gps.wordpress.com/2014/09/12/using-box-as-a-distribution-point-the-9x-version/) due to some unusual circumstances on our end of things.  This has worked really well...except it means manually copying packages from our main Distribution Point every time we or AutoPkgr uploads something.  It'd be handy if AutoPkgr could upload straight to our Box Distribution Point like it can to our other one.

We're still working on a way to keep the two DPs in sync.  We had to use junk AFP info when we set up the Box DP.  This unfortunately means we can't replicate between the two shares.

**Comment by sheagcraig** [comment]
Hmmm. I would say the easiest way to handle this at this time would be to mount the shares yourself and configure them with the Local distribution point type in JSSImporter. I'm not using this method, so maybe they're not mountable.

If they're not mountable, I assume you could just use Box Sync to handle the actual upload, and again use the "Local" DP type to point to your Box folder.

**Comment by rougegoat** [comment]
I wouldn't worry too much on this one.  It's super niche and ended up being one of those "technically possible, but not a good idea" things.  We ended up killing this and switching to Amazon Cloud stuff instead.

**Comment by sheagcraig** [comment]
Alright cool-feel free to reopen it if it makes sense for someone.
