### ISSUE TITLE
Changing Policy Scope

### ISSUE THREAD

**Issue by jshirle2** [sheagcraig/JSSImporter#57]
Hello, 

I've been searching for a tutorial on how to work with overrides and haven't found one that goes into the basics of everything I want to know. The main thing I am working on now is changing the scope of a created policy; I just want it to be scoped to a group "Testing" and that is it. Changing the SmartGroupTemplate.xml doesn't seem to be affecting anything at all and I can't find where this scope would be changed (it just says "scope handled by JSS Importer"). 

I am sure this is a super basic question but any direction is appreciated.

**Comment by sheagcraig** [comment]
Hello back!

So if I'm understanding you correctly, you just want the policy to be scoped to the Testing group? Not to a smart group that includes members of the Testing group who don't have the newest version of the application?

(If so, this means you will have a ton of policies available to those members of the testing group, and picking them apart visually in Self Service  may be troublesome).

But, if that's the case, in your override, make sure that the `groups` argument to JSSImporter has a single array item with a single key of "name" and string value of "Testing". As in
```
<key>groups</key>
<array>
    <dict>
        <key>name</key>
        <string>Testing</string>
   </dict>
</array>

**Comment by jshirle2** [comment]
I made the change you suggested and it doesn't seem to actually register. Here is the full Override: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.AdobeFlashPlayer</string>
	<key>Input</key>
	<dict>
		<key>CATEGORY</key>
		<string>Digital Media</string>
		<key>GROUP_NAME</key>
		<string>AutoPKG-%NAME%-Test</string>
		<key>GROUP_TEMPLATE</key>
		<string>AdobeFlashPlayerSmartGroupTemplate.xml</string>
		<key>NAME</key>
		<string>AdobeFlashPlayer</string>
		<key>POLICY_CATEGORY</key>
		<string>Testing</string>
		<key>POLICY_TEMPLATE</key>
		<string>PolicyTemplate.xml</string>
		<key>SELF_SERVICE_DESCRIPTION</key>
		<string>Adobe Flash Player is freeware software for using content created on the Adobe Flash platform, including viewing multimedia, executing rich Internet applications, and streaming video and audio.</string>
		<key>SELF_SERVICE_ICON</key>
		<string>AdobeFlashPlayer.png</string>
		<key>groups</key>
			<array>
    			<dict>
        		<key>name</key>
        	<string>Testing</string>
   			</dict>
		</array>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.jss-recipes.jss.AdobeFlashPlayer</string>
</dict>
</plist>
```

**Comment by jshirle2** [comment]
Any ideas? I am sure it is really simple but I don't really know enough about the syntax of plists.

**Comment by sheagcraig** [comment]
Using a static group would require changing the actual arguments to the JSSImporter processor. It is not something that can be done with an override. If you look at the recipe you're trying to override, the com.github.jss-recipes.jss.AdobeFlashPlayer, for example, look for the JSSImporter processor and its array of groups. You can copy this recipe and edit it to change the `smart` value to False and name it how you like.

Unfortunately this would potentially mean quite a bit of copying and manual editing of recipes. This also means that every time one of those recipes changes, you're going to have to update them manually. Those of us involved in the JSS-Recipes archive strongly feel that the Smart Group approach is the best use for most people. I would strongly encourage you to try to make use of the smart group as configured. It includes all computers that are members of the testing smart group and only offers the update to computers that do not have that version.

Barring that, I suppose the next easiest thing to do would be to still use the smart group, but edit the smart group template to ONLY include criteria for "Computer Group" "member of" "Testing". (This means trimming out the Application Name and Application Version criteria.

**Comment by sheagcraig** [comment]
Hey @jshirle2! Did you give the above a try? Any feedback? Shall we close the issue?
