### ISSUE TITLE
Enhancement: Add support for uploading packages to Amazon S3

### ISSUE THREAD

**Issue by kitzy** [sheagcraig/JSSImporter#58]
I'm a big fan of using Amazon S3 as the primary distribution point in my JSS, and not having JSSImporter work with it natively is a real bummer.

**Comment by sheagcraig** [comment]
Is that a CDP? I'm guessing no, since CDP's work. The CDP I tested with used Amazon, so help me understand how this could happen!

**Comment by kitzy** [comment]
It is a CDP... I was under the impression that it wouldn't work since there's no configuration options for it in AutoPkgr.

**Comment by sheagcraig** [comment]
Ah, I see what you're getting at. Autopkgr hasn't added the settings in. 

If you set up a JDS in autopkgr, you're 90% there. Then go in and edit the prefs so that instead of type: JDS it's CDP. 

Don't forget to defaults read afterwards!

**Comment by tim-soulen** [comment]
would you provide more details on changing the type to CDP? Not sure where/how to find those preferences in order to change them...thanks!

**Comment by sheagcraig** [comment]
@tim-soulen 
The preferences file for AutoPkg is at `/Library/Preferences/com.github.autopkg.plist`, and the relevant info is here: https://github.com/sheagcraig/JSSImporter#cdp-and-jds-cloud-distribution-point-and-jamf-distribution-servers
