### ISSUE TITLE
Add a note to readme about which characters to avoid in passwords

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSImporter#59]
At least one of these characters was causing somebody trouble on Slack earlier today:
`$*!%`

If I get a few minutes later, I may try to figure out which one specifically doesn't work with JSSImporter when contained in the API_PASSWORD value.

**Comment by sheagcraig** [comment]
Probably $*! All have shell meanings, so if they're adding them incorrectly with defaults write, that could be an issue.

From: Elliot Jordan
Reply-To: sheagcraig/JSSImporter
Date: Tuesday, September 15, 2015 at 2:28 PM
To: sheagcraig/JSSImporter
Subject: [JSSImporter] Add a note to readme about which characters to avoid in passwords (#59)


At least one of these characters was causing somebody trouble on Slack earlier today:
$*!%

If I get a few minutes later, I may try to figure out which one specifically doesn't work with JSSImporter when contained in the API_PASSWORD value.

—
Reply to this email directly or view it on GitHub<https://github.com/sheagcraig/JSSImporter/issues/59>.



This communication (including any attachments) is intended for the use of the intended recipient(s) only and may contain information that is confidential, privileged or legally protected. Any unauthorized use or dissemination of this communication is strictly prohibited. If you have received this communication in error, please immediately notify the sender by return e-mail message and delete all copies of the original communication. Any views or opinions presented are solely those of the author.

**Comment by homebysix** [comment]
I think they used AutoPkgr to set up the API username/password.

**Comment by sheagcraig** [comment]
So do you think there's a difference in the way AutoPkgr is setting passwords from how Defaults would set them?

**Comment by sheagcraig** [comment]
BTW I feel like this is a pretty common issue-how can we make it more resilient?

**Comment by sheagcraig** [comment]
@homebysix ever figure out what the smoking gun No-No password character was/were/is?

**Comment by sheagcraig** [comment]
Put in a paragraph about passwords. I think we're covered here. Until someone can figure out what _exactly_ is going wrong.

**Comment by homebysix** [comment]
$ounds ¢∞d †° m∑
