### ISSUE TITLE
0.5.0 Package fails to install on El Capitan

### ISSUE THREAD

**Issue by jameslbrown** [sheagcraig/JSSImporter#60]
Installing from the JSSImporter-0.5.0.pkg gives:

This package is incompatible with this version of OS X and may fail to install. Installing this package may damage your system, and the installation may fail. To stop the program and the installation, click “Cancel Installation”.

Naturally, I click on "Install Anyway" :-)

Get: "There were errors with the installation. You may want to try installing" then it gets cut off. Dialog says, "The Installation failed. The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

Maybe it's a problem with SIP?

Console shows:

18/9/2015 3:40:07.791 PM UserEventAgent[51]: Failed to send message because the port couldn't be created.
18/9/2015 3:40:07.000 PM kernel[0]: Sandbox: shove(20268) System Policy: deny(1) file-write-create /usr/share/jssimporter
18/9/2015 3:40:08.430 PM UserEventAgent[51]: Failed to send message because the port couldn't be created.
18/9/2015 3:40:08.739 PM Installer[20128]: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

Running GM version of OS X 10.11

James.

**Comment by sheagcraig** [comment]
Thanks for the heads up. I'll look into it on our test machine. 

I thought /use/share was supposed to be allowed with sip? Time to read up!

**Comment by jameslbrown** [comment]
<i>I thought /use/share was supposed to be allowed with sip? </i>

I don't know - it was just a guess!

**Comment by damacguy** [comment]
Only /usr/local is accessible with SIP. So, /usr/local/share would work, but not /usr/share.

https://developer.apple.com/library/prerelease/ios/documentation/Security/Conceptual/System_Integrity_Protection_Guide/FileSystemProtections/FileSystemProtections.html

**Comment by sheagcraig** [comment]
Alright!
