### ISSUE TITLE
With Casper 9.8.1 seeing 504 errors...

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/JSSImporter#62]
Seeing this error and not sure why:
local.jss.UNCSystem-AutoPKG-Google Earth    Error in local.jss.UNCSystem-AutoPKG-Google Earth: Processor: JSSImporter: Error: Response Code: 504 Response:  Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1459, in run_recipes autopackager.process(recipe) File "/Library/AutoPkg/autopkglib/**init**.py", line 479, in process % (identifier, step["Processor"], unicode(err))) AutoPackagerError: Error in local.jss.UNCSystem-AutoPKG-Google Earth: Processor: JSSImporter: Error: Response Code: 504 Response:

**Comment by sheagcraig** [comment]
I'm not sure on this... I've never seen a 504. Here's the generic description of a 504:
```
10.5.5 504 Gateway Timeout

The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server specified by the URI (e.g. HTTP, FTP, LDAP) or some other auxiliary server (e.g. DNS) it needed to access in attempting to complete the request.

      Note: Note to implementors: some deployed proxies are known to
      return 400 or 500 when DNS lookups time out.
```

**Comment by sheagcraig** [comment]
@everetteallen Is this issue still going on for you? Does it coincide with any network changes or infrastructure changes?

**Comment by everetteallen** [comment]
Shea,
This is still happening less often but still issue.  Also there are no 
known network or infrastructure changes when it occurs.
Thanks!


On 3/23/16 10:06 AM, Shea Craig wrote:
> @everetteallen <https://github.com/everetteallen> Is this issue still
> going on for you? Does it coincide with any network changes or
> infrastructure changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sheagcraig/JSSImporter/issues/62#issuecomment-200358644>
>

-- 
Everette Gray Allen		Systems Programmer II
Office of Information Technology	Apple Support Specialist
2620 Hillsborough St, Campus Box 7109
Raleigh, NC 27695-7109  AIM: EveretteAlln
919-515-4558		Everette_Allen@ncsu.edu

**Comment by sheagcraig** [comment]
Hey @everetteallen: Any updates on this? Have you come up with any trigger for when it happens? Do you think we should keep the issue open?

**Comment by sheagcraig** [comment]
Closing due to no update in a year.
