### ISSUE TITLE
Python-JSS Issues in v0.5.1

### ISSUE THREAD

**Issue by rougegoat** [sheagcraig/JSSImporter#63]
I just updated JSS Importer in AutoPkgr and came across two related problems with python-jss.
1. JSS Importer downgraded the installed version of python-jss from 1.4 to 1.3.  I had recently installed jss_helper on the machine in question and had a lot of trouble getting easy_install to actually download version 1.4.  As a result, I can say without a doubt that the machine had previously had 1.4 on it.  I am assuming that python-jss is a system wide thing and not something every app installs its own version of.
2. JSS Importer gave no feedback alerting me that the reason none of my packages were uploading to the JSS was the now out of date python-jss on the machine.  Instead, policies just stopped running on AutoPkgr.  No error was thrown for the user to see that things weren't wonky.

**Comment by sheagcraig** [comment]
The package for JSSImporter includes an egg for the newest python-jss,
which it installs; then it tries to update from the web. This is to prevent
people with no internet connection or a proxy from not being able to
install.

I imagine it installed the 1.4.0 egg and then the easy_install update is
what rolled it back. Which doesn't make sense since I can do `sudo
easy_install -Un python-jss` to dry-run it and it sees 1.4.0 as the newest,
not 1.3.

As for number 2, diagnosing or even getting error notifications in AutoPkgr
is sometimes iffy. I'll mention it to the team.

**Comment by sheagcraig** [comment]
BTW-what did you end up having to do to get easy_install to get the newer
version?

**Comment by rougegoat** [comment]
Nothing I can replicate.  On one machine it successfully worked with easy_install, but I haven't really tried it since then.  I know today it didn't work after the above issues.  I ended up using pip to install it.

**Comment by homebysix** [comment]
I also ran into this issue. Here's what I did:

1. Installed JSSImporter 0.5.1 on a Mac with 0.5.0 already installed.
2. After installation, tried to run a .jss recipe. Got the error: `JSSImporter: Requires python-jss version: 1.4. Installed: 1.3`
3. Ran `sudo pip install python-jss --upgrade`
4. Ran the .jss recipe again. It succeeded.

So it seems that the JSSImporter package isn't doing the python-jss upgrade as expected.

**Comment by sheagcraig** [comment]
@homebysix Heard anything more about this issue?

**Comment by rougegoat** [comment]
I haven't seen it in recent versions.

**Comment by sheagcraig** [comment]
I think part of the issue must be that there's a mix of pip and easy_install going on. The JSSImporter package uses easy_install. I think the instructions for JSSImporter, however, specify pip for manual install. I'll look into this and see if I can come up with something.

**Comment by sheagcraig** [comment]
1.0.0 will be getting rid of pip or easy installing anything. So this can be closed.
