### ISSUE TITLE
Feature request: Automatic parsing of os_requirements into smart groups

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/JSSImporter#65]
Something like the ideas mentioned in this thread:
https://github.com/autopkg/jss-recipes/pull/35

**Comment by sheagcraig** [comment]
I'll look at this for the next version.

**Comment by novaksam** [comment]
This would be pretty super duper, though I can see it not working in all instances because not all packages are created equal (not always possible to get to the Info.plist).

**Comment by sheagcraig** [comment]
This is outside of my ability to develop at this time. Anybody who wants to take a stab at it is welcome to do so, but I don't feel comfortable trying to implement this at this time since I'm not using Jamf Pro.
