### ISSUE TITLE
Error mounting url

### ISSUE THREAD

**Issue by Chriskmpruitt** [sheagcraig/JSSImporter#74]
Hello everyone!

I have been playing around with autopkg the passed couple days and would love to get it working.
It looks like everything is working until it has to talk to the JSS. It mounts our CasperShare but give me this error.

Error mounting Url "smb://jssuser:jsspassord:@ourjss:139/caspershare$: None

defaults read com.github.autopkg JSS_REPOS - looks right
defaults read com.github.autopkg JSS_URL - looks right
defaults read com.github.autopkg JSS_VERIFY_SSL - says no SSL exists 
defaults read com.github.autopkg API_USERNAME - looks good
defaults read com.github.autopkg API_PASSWORD - looks good

**Comment by Chriskmpruitt** [comment]
![screen shot 2015-12-31 at 8 43 03 am](https://cloud.githubusercontent.com/assets/7968380/12066867/abb50a6c-af9b-11e5-9db0-f3f5ef0176ec.png)

**Comment by sheagcraig** [comment]
Hi Chris,
So by "looks right", what do you see when you `defaults read /Library/Preferences/com.github.autopkg JSS_REPOS`? Obviously remove any URL's or anything that references private information, but I would like to see the actual output.

**Comment by Chriskmpruitt** [comment]
Output

(       
        {
          name = Name of casper distribution point;
          Password = Password for read/right account for that distribution point

       }

)

**Comment by sheagcraig** [comment]
What is that $ doing at the end... Is there a newline also? Or is that just AutoPkgr wrapping the text?

Given the URL output in the AutoPkgr error message, can you mount that share in Finder (Connect to Server) or on the commandline?

Is it definitely port 139 and not 445?

Does the password have any XML or bash reserved characters in it that may be getting encoded incorrectly?

**Comment by Chriskmpruitt** [comment]
Thank you for helping out shegcraig!

We have the $ in our smb share name just to hide it

I can manually mount the Distribution point no problem. But also when i run the AutoPkg recipes it mounts the Distribution point.

And it for sure is on port 139 

our password does not have any XML or bash reserved characters.

**Comment by sheagcraig** [comment]
So AutoPkg will mount the distribution point, but not AutoPkgr?

**Comment by Chriskmpruitt** [comment]
no they both mount the distribution point. That is the last step it completes before giving me that error.

**Comment by Chriskmpruitt** [comment]
We figured it out! does not respect the $

**Comment by sheagcraig** [comment]
That's super weird that it actually mounts, but it still has issues. The mount used to be done by shelling out to the mount_smbfs command, but it does it at a lower level now, so I'm surprised it has issues. But everything is good now?

**Comment by Chriskmpruitt** [comment]
Yes its seems to be working without the $ in the distribution points name. It is able to read/write to our JSS. And might i say AutoPkg is AWESOME! thank you!

**Comment by bytesman** [comment]
Hi Guys, I have the same problem, however I do not have a $ in my share. AutoPkg mounts the drive and I can read and write to it. But I get the same error message. I am mounting a afp, and I am running this on a 10.11.3 machine.

**Comment by sheagcraig** [comment]
Hi @bytesman 
So you get the "error mounting URL" error, but it actually mounts it?

**Comment by bytesman** [comment]
Yes the drive is mounted and I can write into it. I disconnect it and then AutoPkgr/JSSImporter remounts it if I run the update process.

**Comment by sheagcraig** [comment]
I believe @Chriskmpruitt is all set here. @bytesman are you still trying to get this working, or are you all set?

**Comment by bytesman** [comment]
Yes even with the new version still the same problem.

**Comment by cjduckk** [comment]
@Chriskmpruitt How were you able to resolve this?  Did you just change your distribution point to not have a "$" at the end, or is there another workaround?

**Comment by Chriskmpruitt** [comment]
@cjduckk  Yes when trying to mount the distribution point, it was not respecting the $ in the name. Change the Share name and now autopkg connects without a problem. 👍

**Comment by ss-whiterun** [comment]
I am also having this error in AutoPkgr version 1.4.1(1308). Manual mount to smb share works fine, but when running recipes reports 

"Error mounting url "smb://casperusername:pass@IPOFSERVER:PORT/Distribution_Share": None"

I have checked that the share is not mounted, and that the information in the JSS_REPOS variable is correct. 

The recipe creates the pkg file successfully - it is only at the connection to JSS where it fails. 

The machine I am running it on is OS X 10.11.6 and is not managed by Casper. The Distribution Share is not hidden by $

**Comment by patgmac** [comment]
I am seeing this same problem to our dev server (seeing different issue in prod). Has anyone figured out a solution? Also not using $ in the share name.

**Comment by sheagcraig** [comment]
OP issue was a $ in the share name.

Other folks who have commented on here, an update:
JSSImporter testing branch will only mount shares that aren't already mounted, and it won't unmount shares that were mounted prior the JSSImporter run. SO, at least to get working, mount your shares and carry on.

If JSSImporter still can't mount your shares, get on the Macadmins Slack and ask around there, and include your config file and/or open an issue with your exact issue here and let's all help each other out.

Frequent issues tend to be using a different port than normal SMB; the automatic DP setting detection is just pulling data from however it is configured on the JSS. Even if Casper Admin can mount it fine, doesn't mean it's going to translate.

Passwords with certain characters may be an issue, although we're not shelling out to `mount` so I hope that's not an issue.
