### ISSUE TITLE
check if pkg_path exists

### ISSUE THREAD

**Issue by systemheld** [sheagcraig/JSSImporter#76]
there should definitely thrown an error if the file defined in the pkg_path input variable does not exist. Currently there is no notification and the policy just runs ...

**Comment by sheagcraig** [comment]
I can throw this in the next time I work through the code. I would hope that this situation is extremely unlikely, but that doesn't mean we can't test for it.

**Comment by sheagcraig** [comment]
I would think that should never happen, but obviously it does! I'll put this in the next time I go through the code.

**Comment by ocoda** [comment]
I had a parent recipe which returned a faulty pkg name. I admit that this is a rare case :-)

**Comment by sheagcraig** [comment]
This has been added to the 1.0.0 release that is in the testing branch at the moment. Please let me know if it doesn't work!
