### ISSUE TITLE
Feature Request - Multiple Policy update

### ISSUE THREAD

**Issue by novaksam** [sheagcraig/JSSImporter#77]
I'm not sure how it'd be done, but it'd be sweet if we were able to update multiple policies with one recipe. Primarily looking to update the PKG that is installed by the policies.

**Comment by sheagcraig** [comment]
Hey @novaksam 
So this is actually already possible, although you're going to have to write the recipes yourself. Any recipe can have an arbitrary number of JSSImporter stages. To get them to do anything useful, you may have to manipulate some of the environment variables in-between JSSImporters to get them to do something different.
