### ISSUE TITLE
Permission denied on mounted server

### ISSUE THREAD

**Issue by agerstein** [sheagcraig/JSSImporter#79]
At least once a week, I get a message from AutoPkgr indicating:

> Error in local.jss.Microsoft Excel: Processor: JSSImporter: Error: [Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft Excel-15.19.1.pkg'	

The traceback isn't more descriptive:

> Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1461, in run_recipes autopackager.process(recipe) File "/Library/AutoPkg/autopkglib/__init__.py", line 479, in process % (identifier, step["Processor"], unicode(err))) AutoPackagerError: Error in local.jss.Microsoft Excel: Processor: JSSImporter: Error: [Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft Excel-15.19.1.pkg'

I've tested the file share by mounting it manually and it shows up ok. I've verified that the account has permissions to read/write to the share/sub folders - no issues.

Looking at the system.log, I see:
`Feb 29 13:11:21 oitajg067324 kernel[0]: AFP_VFS afpfs_unmount: /Volumes/CasperShare, flags 524288, pid 3536
Feb 29 13:11:21 oitajg067324 kernel[0]: ASP_TCP Disconnect: triggering reconnect by bumping reconnTrigger from curr value 0 on so 0xffffff803e598000
Feb 29 13:11:22 oitajg067324 kernel[0]: ASP_TCP Detach: Reply queue not empty?
Feb 29 13:11:22 oitajg067324 com.apple.xpc.launchd[1] (com.apple.quicklook[3539]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 29 13:11:25 oitajg067324 AutoPkgr[1546]: Error [7] Error running recipes 
	 [Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft Excel-15.19.1.pkg'
	
	[Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft OneNote-15.19.1.pkg'
	
	[Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft Outlook-15.19.1.pkg'
	
	[Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft PowerPoint-15.19.1.pkg'
	
	[Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Microsoft Word-15.19.1.pkg'
	
	[Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/AdobeReaderDC-15.010.20056.pkg'
	
	[Errno 13] Permission denied: u'/Volumes/CasperShare/Packages/Audacity-2.1.2.0.pkg'`

If I'm reading that properly, it's trying to unmount the CasperShare volume, then it tries to reconnect, and then it can't?

**Comment by sheagcraig** [comment]
I'm not sure if all of those errors pertain to the mount. The line about quicklook / xpc.launchd specifically.

I would think an unmounted share wouldn't trigger a permission denied error, but I could be wrong.

It sounds like you're running a recipe list rather than a single recipe. Does it work for one or more recipes and then stop working midway through the run? JSSImporter _does_ unmount after each run, so perhaps the OS can't keep up?

**Comment by agerstein** [comment]
I'm not sure that the quicklook/xpc.launchd is related - I copied/pasted log files, so there might have been more than I meant. On the other hand, who knows...

I'm using AutoPkgr to do it's things with a bunch of my selected recipes, and then it's interacting with JSSImporter. In the interest of troubleshooting (or making this harder on myself) I went into the recipe_list.txt and re-arranged things a little - for example, it always seems to have an issue with the MS Office 2016 updates, so I moved them apart and put some other things between them. Other than that, it's going to  be a waiting game. I did just reboot our Casper server, which was being dog slow - so maybe that was a factor?

Is there something I can do to get more logging? There doesn't seem to be any thing in the system.log for JSSImporter.

**Comment by sheagcraig** [comment]
Any updates on this @agerstein? Are you still experiencing this issue, or did it somehow work itself out? If you fixed it, can you share the fix here?

Thanks!

**Comment by agerstein** [comment]
Sorry, but yes, re-arranging things seems to have fixed the issue - thanks!

**Comment by agerstein** [comment]
I meant to close it....
