### ISSUE TITLE
Futures??

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/JSSImporter#80]
So note sure this is the right place but it looks like Shea's focus has shifted more to Munki and I am wondering if JSSImporter will continue to keep pace with Casper changes?
Thanks!

**Comment by sheagcraig** [comment]
Hey Everette,
Like any good open-source project, I'm always open to pull requests.

I asked around recently if there was anything that I had missed from recent JAMF announcements/releases in terms of new features that I needed to support in either python-jss or JSSImporter, and I didn't hear anything.

I haven't been able to do any development time or work on the issues for these products, but anyone who can send me code that they've tested that I can pull in would be able to contribute.

**Comment by everetteallen** [comment]
Thanks I will work with that in mind.
