### ISSUE TITLE
Error Mounting AFP Volume

### ISSUE THREAD

**Issue by zacharysfisher** [sheagcraig/JSSImporter#82]
I get the following error:

Error mounting url "afp://read.only:*******@10.1.8.11:548/JSS/JSS_dropbox": None

However if I try to manually mount the volume it works of course.  Any ideas?

**Comment by sheagcraig** [comment]
The most common issues around mounting file shares have are:
1. Password with reserved characters not getting encoded properly (e.g. do you have `!` or some other character in the password that is getting munged by going through bash/defaults to XML/plist to python to objective-C?)
2. Slight mistakes in mount configuration.

Are you using AutoPkg or AutoPkgr? If so, are you using the newest AutoPkgr, which improves the mounting dialog.

Does Casper Admin successfully mount the shares upon opening?

Please provide a sanitized version of your AutoPkg preferences (don't expose username/password/URL info) and we'll go from there.

**Comment by zacharyfisher** [comment]
Would it be possible to change what user it tries to use to connect to Distribution point?  Right now obviously it is using a read.only account however that password has aspecial characters in it which might be causing issues.  How can i change lets say read.only to like an administrator or autopkgr username instead?

**Comment by zacharyfisher** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>API_PASSWORD</key>
	<string>********</string>
	<key>API_USERNAME</key>
	<string>********</string>
	<key>GIT_PATH</key>
	<string>/Applications/Xcode.app/Contents/Developer/usr/bin/git</string>
	<key>JSS_REPOS</key>
	<array>
		<dict>
			<key>name</key>
			<string>TSS_dropbox</string>
			<key>password</key>
			<string>***********</string>
		</dict>
	</array>
	<key>JSS_URL</key>
	<string>JSS URL</string>
	<key>JSS_VERIFY_SSL</key>
	<false/>
	<key>RECIPE_REPOS</key>
	<dict>
		<key>/Users/zachary.fisher/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes</key>
		<dict>
			<key>URL</key>
			<string>https://github.com/autopkg/jss-recipes.git</string>
		</dict>
		<key>/Users/zachary.fisher/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes</key>
		<dict>
			<key>URL</key>
			<string>https://github.com/autopkg/justinrummel-recipes.git</string>
		</dict>
		<key>/Users/zachary.fisher/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes</key>
		<dict>
			<key>URL</key>
			<string>https://github.com/autopkg/recipes.git</string>
		</dict>
	</dict>
	<key>RECIPE_SEARCH_DIRS</key>
	<array>
		<string>.</string>
		<string>~/Library/AutoPkg/Recipes</string>
		<string>/Library/AutoPkg/Recipes</string>
		<string>/Users/zachary.fisher/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes</string>
		<string>/Users/zachary.fisher/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes</string>
		<string>/Users/zachary.fisher/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes</string>
	</array>
</dict>
</plist>

**Comment by sheagcraig** [comment]
Hey @zacharyfisher. So there are definitely a few characters in passwords that seem to always cause problems. I think we're still collectively trying to figure out _which_, but probably any of these: `$*!%`.

If you have control of that account, I would just change the password.

Otherwise, do you have any updates on this? Were you able to solve it on your own? Based on your configuration above, you're definitely using the correct "auto" repo setup, provided the share is also correctly configured in the JSS web panel (which I'm sure it is because you'd know when you couldn't get the DP to mount in Casper Admin).
