### ISSUE TITLE
TLS 1.2 only Casper Servers break JSSImporter

### ISSUE THREAD

**Issue by erikng** [sheagcraig/JSSImporter#89]
`Error: __str__ returned non-string (type Error)` when running autopkg recipes.

I upgraded to the latest version of python-jss and the issue still persisted.

**Comment by janorn** [comment]
I have experienced the same issue!
Found this https://github.com/kennethreitz/requests/issues/2022 seems to be an issue with the very old openssl in OSX.

**Comment by janorn** [comment]
I got these error messages when running recipes:

```
The following recipes failed:
    VirtualBox.jss
        Error in com.github.jss-recipes.jss.VirtualBox: Processor: JSSImporter: Error: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
```

Enable TLSv1.0 and/or TLSv1.1 solved this for me. But I guess the best way forward is to use brew and install a new openssl.

**Comment by sheagcraig** [comment]
I'm working on an update to python-jss that uses Curl by default, so we won't even have to deal with Requests unless we want to. Stay tuned.

**Comment by erikng** [comment]
You might also want to look into claytons Vendored package. It allows you to "upgrade" OpenSSL.

________________________________

**Comment by sheagcraig** [comment]
Folks interested in this issue, check out the testing branch of python-jss and of JSSImporter. Together, they should be able to do TLS1.2 by just using the system curl.
