### ISSUE TITLE
Server uses a self signed CA, plist set to ignore, still showing issues.

### ISSUE THREAD

**Issue by lucid772** [sheagcraig/JSSImporter#9]
Please see the comments and issue at https://github.com/lindegroup/autopkgr/issues/178#issuecomment-61215581

**Comment by sheagcraig** [comment]
@ocoda Just wanted to let you know that I discovered there is a built-in way in requests to use TLS over SSLv23: http://docs.python-requests.org/en/latest/user/advanced/#transport-adapters

Here is python-jss' usage of it:
https://github.com/sheagcraig/python-jss/blob/master/jss/tlsadapter.py

**Comment by ocoda** [comment]
@sheagcraig Thanks for pointing out, that will make things a lot easier in some of my scripts!
