### ISSUE TITLE
Allow Exclusion Groups when Scoping Policies

### ISSUE THREAD

**Issue by BadStreff** [sheagcraig/JSSImporter#92]
It would be nice if we could exclude groups from policies that have been created by templates. I currently have a stripped down JSSImporter processor specifically for creating policies and groups (where I have implemented this) and thought maybe this is something other users might find useful in the main processor?

Is this something that is planned to be implemented? I did a search through the issues and did find one person that was asking about excluding certain groups. Looks for advice on the best way to submit a PR. I currently just added a key 'exclusion_groups' that work similar to the 'groups' key except it excludes a group.

**Comment by sheagcraig** [comment]
Added per your PR sir!
