### ISSUE TITLE
Support Multi JSS

### ISSUE THREAD

**Issue by bdelamarche** [sheagcraig/JSSImporter#98]
Hello,

Do you think it is possible to develop a functionality that allows to write policies and packages on multiple JSS instances ?

Thank you

**Comment by sheagcraig** [comment]
It's very much possible. AutoPkg just sits on all of the built packages, so the simplest approach would probably be to just run it again, but with a second set of preferences supplied for AutoPkg, referencing the second/third/etc server for each run.

Setting up the preference system for JSSImporter/python-jss to handle this with a single jss.recipe would be very cluttered I would think.

Also, FWIW, if there's any difference between the JSS's, it's not as simple as just posting the same data; there could be ID disparities, etc. And JSSImporter would have to grow the ability to decide whether two policies were indeed the same or not, between multiple JSSs.

I would say you could get 100% of that by just running AutoPkg multiple times, swapping out the prefs. You could do it on multiple machines, you could do it as different users and have the differing parts in user prefs, etc.
