### ISSUE TITLE
Allow turning off everything but package upload

### ISSUE THREAD

**Issue by magnusviri** [sheagcraig/JSSImporter#99]
I've been trying to get AutoPkg setup and running for my Jamf server and I think my biggest hurdle has been the JSSImporter adding policies, scripts, extension attributes, etc.  I do not want the settings that are specified in the default com.github.autopkg.jss-recipes recipes but overrides can only remove some of them.  For example, extension attributes and scripts can't be turned off.

Implementing this could just be as easy as a preference.

I also think all of these things should be off by default because it's very difficult for a newbie to Jamf and AutoPkg to figure out what is going on.  I've been working on this for a while and I think I've finally wrapped my head around what is going on and I actually don't want them so I've commented the lines out in the JSSImporter.py file because I can't see any other way to disable them.

**Comment by sheagcraig** [comment]
The jss-recipes repo is a recommended best-practice as developed by admins at several enterprise and education sites. In general, we really feel like this is the best first approach; it's complicated, but that's the nature of the beast.

I would think that the best approach if you only want to automate putting the packages onto the distribution points would depend on what type of DP you have. If it's just a file share, the output of AutoPkg pkg recipes is what you're looking for. Then just copy new ones any one of a number of ways.

If you're stuck with a cloud distribution point, things get a little more complicated. It's our recommendation that you have overrides for every recipe you intend on using in your organization _anyway_; indeed, you'll need to for AutoPkg 1.0. If all you want to do is upload packages, you should be able to create a base jss.recipe that would do just that, and not do anything else. It would just need to inherit from a pkg.recipe of the product you're interested in.
